resolver: lts-21.19
system-ghc: true

packages:
- '.'

extra-deps: []

# XXX: GHC 9.2.1-capable set
#- base-compat-0.12.1
#- base-compat-batteries-0.12.1
#- aeson-2.0.3.0
#- text-2.0
#- hashable-1.4.0.2

flags:
  aeson-tiled:
    tests: true
