on: [push, pull_request]

name: build

jobs:
  build: # TODO: split by OS
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        ghc: ['8.10', '9.0', '9.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal build --only-dependencies -j2
      - run: cabal build
